name: build_and_test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: make build
      
    - name: Test
      env:
        GO_TEST_RES_PATH: test_ret_${{ github.ref_name }}
      run: |
        commit_id=$(git rev-parse --short HEAD)
        file=$GO_TEST_RES_PATH'_'$commit_id'_'$(date +%Y%m%d-%H%M%S)'.log'
        make test > $file
        cat $file
        tree
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.out
        name: idgen
        verbose: true
